apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJVMmxzYVc1TGFYSnBiR3c2WjJod1gxTkRPR2R5YUhCdFkyMUdRekV5VUdWRVJHSnJaRE5JWW1oRFJFZFNhVEZEVG10YVZBPT0ifX19
type: kubernetes.io/dockerconfigjson
